config/routes.rb
Rails.application.routes.draw do

  resources :roles do
    collection do
      get :manage
      post :rebuild
    end
  end
  resources :departments
  resources :acronyms
  resources :areas do
    collection do
      get :manage
      post :rebuild
    end
  end

  resources :levels do
    collection do
      get :manage

      post :rebuild
    end
  end

  resources :board, only: [:index, :destroy] do
    member do
      put 'confirm'
      put 'banish'
      put 'welcome'
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }
  resources :register_models

  root 'register_models#index'

end

app/views/menus/_admin_links.html.erb
<%= link_to 'Acronyms', acronyms_url %>
<%= link_to 'Roles', manage_roles_url %>
<%= link_to 'Departments', departments_url %>
<%= link_to 'Levels', manage_levels_url %>
<%= link_to 'Areas',  manage_areas_url %>
<%= link_to 'Board' , board_index_url %>

app/views/menus/_header.html.erb
<div id="header">
	<div class="Profile">
	<%= render 'devise/menu/profile' %>
	</div>

	<div class="Logo">
	  <%= link_to 'Q', root_url, :class => 'BlankLink' %>
	</div>

	<div style="clear:both;"></div>

	<div id="upper_menu">
		<%= render 'menus/admin_links'if you_are_admin? %>
	</div>

    <%= render 'menus/messages' %>
</div>

app/views/menus/_messages.html.erb
<% flash.each do |key, value| %>
  <% if key != "notice" %>
    <p class="alert alert-<%= key %>">
          <%= value %>
    </p>
  <% end %>
<% end %>