config/routes.rb
Rails.application.routes.draw do

  resources :roles do
    collection do
      get :manage
      post :rebuild
    end
  end
  resources :departments
  resources :acronyms
  resources :areas do
    collection do
      get :manage
      post :rebuild
    end
  end

  resources :levels do
    collection do
      get :manage

      post :rebuild
    end
  end

  resources :board, only: [:index, :destroy] do
    member do
      put 'confirm'
      put 'banish'
      put 'welcome'
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }
  resources :register_models

  root 'register_models#index'

end

app/models/area.rb
require 'formatter'

class Area < ActiveRecord::Base
	acts_as_nested_set
	include TheSortableTree::Scopes

	has_and_belongs_to_many :levels

    validates :name, uniqueness: true
    validate :leaf_level

    def leaf_level
        if levels.any? and  !self.leaf?
            errors.add(:base, "Only terminal areas can be linked to levels. #{Formatter.show name} is not terminal." )
        end
    end

    def title
    	name
    end

    def parent_name
    	return "No Parent" if root?
    	return parent.name
    end


    # True if this area is descendant of given area or is the given area.
    def comes_from? area
        area = area.to_s if area.is_a? Symbol
        area = Area.find_by(name: area) if area.is_a? String

        self.self_and_ancestors.include? area
    end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  include TheSortableTreeController::Rebuild

  before_action :check_admin_privileges
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def manage
    @areas = Area.nested_set.select('id, name, parent_id').all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :parent_id, :lft, :rgt, :depth, :children_count, {level_ids: []})
    end
end

app/helpers/areas_helper.rb
module AreasHelper


end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%#= f.number_field :parent_id %>
    <%= select_tag "area[parent_id]", nested_options(Area.all, :selected => @area.parent), class: :nested_options, include_blank: true %>
  </div>

  <div class="field">
  <h3>Related Levels</h3>
    <%= hidden_field_tag 'area[level_ids][]', nil %>
    <%= traverse_tree(Level.roots) do |level| %>
          <%= show_checkbox(@area, level, disabled: !level.leaf?) %> <br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', manage_areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Depth</th>
      <th>Children count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.parent_name %></td>
        <td><%= area.depth %></td>
        <td><%= area.children_count %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/manage.html.erb
<%= link_to 'New Area', new_area_path %>
<ol class="sortable_tree" data-rebuild_url="<%= rebuild_areas_url -%>" >
  <%=  build_server_tree(beautify(@areas), type: :sortable, linked_with: :levels) %>
</ol>
<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>
     <%= pretty @area.name %>
  </h2>
  <em>
  ( Depth:
     <%= @area.depth %>
  )
  </em>
</p>

<p>
  <strong>Parent:</strong>
  <%= pretty @area.parent_name %>
</p>


<% if @area.children.count != 0 %>
  <p>
    <strong>
    Children
    ( <%= @area.children.count %>): </strong>
    <br/>
    <em> <%= show_together @area.children %></em>
  </p>

<% end %>

<p>
  <strong>Levels:</strong>
  <%= show_together @area.levels %>
</p>
<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', manage_areas_path %>