config/routes.rb
Rails.application.routes.draw do

  resources :roles do
    collection do
      get :manage
      post :rebuild
    end
  end
  resources :departments
  resources :acronyms
  resources :areas do
    collection do
      get :manage
      post :rebuild
    end
  end

  resources :levels do
    collection do
      get :manage

      post :rebuild
    end
  end

  resources :board, only: [:index, :destroy] do
    member do
      put 'confirm'
      put 'banish'
      put 'welcome'
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }
  resources :register_models

  root 'register_models#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
	acts_as_nested_set
	include TheSortableTree::Scopes

	validates :name, uniqueness: true

	def title
		name
	end

	def parent_name
    	return "No Parent" if root?
    	return parent.name
    end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include TheSortableTreeController::Rebuild

  before_action :check_admin_privileges
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def manage
    @roles = Role.nested_set.select('id, name, parent_id').all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :parent_id, :lft, :rgt, :depth, :children_count)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= select_tag "role[parent_id]", nested_options(Role.all, :selected => @role.parent), class: :nested_options, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', manage_roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Lft</th>
      <th>Rgt</th>
      <th>Depth</th>
      <th>Children count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.parent %></td>
        <td><%= role.lft %></td>
        <td><%= role.rgt %></td>
        <td><%= role.depth %></td>
        <td><%= role.children_count %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/manage.html.erb
<%= link_to 'New Role', new_role_path %>
<ol class="sortable_tree" data-rebuild_url="<%= rebuild_roles_url -%>" >
  <%=  build_server_tree(beautify(@roles), type: :sortable) %>
</ol>
<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h2><%= pretty @role.name %></h2>

  <em>
  (
  level
  <%= @role.depth %>
  )
  </em>
</p>

<p>
  <strong>Parent:</strong>
  <%= @role.parent_name %>
</p>

<% if @role.children.count != 0 %>
<p>
  <strong>Children (<%= @role.children.count %>): </strong>
  <em> <%= show_together @role.children %></em>
</p>
<% end %>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', manage_roles_path %>