config/routes.rb
Rails.application.routes.draw do

  resources :roles do
    collection do
      get :manage
      post :rebuild
    end
  end
  resources :departments
  resources :acronyms
  resources :areas do
    collection do
      get :manage
      post :rebuild
    end
  end

  resources :levels do
    collection do
      get :manage

      post :rebuild
    end
  end

  resources :board, only: [:index, :destroy] do
    member do
      put 'confirm'
      put 'banish'
      put 'welcome'
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }
  resources :register_models

  root 'register_models#index'

end

app/models/level.rb
require 'formatter'

class Level < ActiveRecord::Base

	acts_as_nested_set
	include TheSortableTree::Scopes

	has_and_belongs_to_many :areas

    validates :name, uniqueness: true
    validate :leaf_level

    def leaf_level
        if areas.any? and  !leaf?
            errors.add(:base, "Only terminal levels can be linked to areas. #{Formatter.show self.name} is not terminal." )
        end
    end

    def title
    	name
    end

    def parent_name
    	return "No Parent" if root?
    	return parent.name
    end

    # True if an area that comes from given area
    # is offered in this level or any of the sublevels
    def offers? area
         area = normalize(area)
         self.self_and_descendants.inject(false) do |found, level|
            level.areas.inject(found) do |found, a|
                found || a.comes_from?(area)
            end
         end
    end

    # True if
    # all of the sublevels have at least one area that comes from given area.
    def has? area
        area = normalize(area)
        self.children.inject(true) do |all, ch|
            all &&
            ch.self_and_descendants.inject(false) do |some, level|
                some || level.areas.inject(some) { |some, ar| some || ar.comes_from?(area) }
            end
        end
    end

    # find a record using record name or acronym
    def find_me name

    end

    private

    def normalize area
        area = area.to_s if area.is_a? Symbol
        area = Area.find_by(name: area) if area.is_a? String
        area
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  include TheSortableTreeController::Rebuild

  before_action :check_admin_privileges
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def manage
    @levels = Level.nested_set.select('id, name, parent_id').all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :parent_id, :lft, :rgt, :depth, :children_count, {area_ids: []})
    end
end

app/helpers/levels_helper.rb
module LevelsHelper

end

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%#= f.collection_select :parent_id, Level.all, :id, :name %>
    <%= select_tag "level[parent_id]", nested_options(Level.all, :selected => @level.parent), class: :nested_options, include_blank: true %>
  </div>

  <div class="field">
  <h3> Related Areas </h3>
  <%= hidden_field_tag 'level[area_ids][]', nil %>
    <%= traverse_tree(Area.roots) do |area| %>
          <%= show_checkbox(@level, area, disabled: !area.leaf?) %> <br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', manage_levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Depth</th>
      <th>Children count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.parent_name %></td>
        <td><%= level.depth %></td>
        <td><%= level.children_count %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/manage.html.erb
<%= link_to 'New Level', new_level_path %>
<ol class="sortable_tree" data-rebuild_url="<%= rebuild_levels_url -%>" >
  <%=  build_server_tree(beautify(@levels), type: :sortable, linked_with: :areas) %>
</ol>
<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= pretty @level.name %></h2>

  <em>
  (
  level
  <%= @level.depth %>
  )
  </em>

</p>

<p>
  <strong>Belongs to:</strong>
  <%= pretty @level.parent_name %>
</p>

<% if @level.children.count != 0 %>
  <p>
    <strong>
    Children
    ( <%= @level.children.count %>): </strong>
    <br/>
    <em> <%= show_together @level.children %></em>
  </p>

<% end %>

<p>
  <strong>Areas:</strong>
  <%= show_together @level.areas %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', manage_levels_path %>